name: TF Pre-Commit

permissions: {}

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  main:
    uses: getindata/github-workflows/.github/workflows/tf-pre-commit.yml@v0.3.1
    with:
      tflint-version: v0.46.0
